# Wire up travis
language: python

python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -e .[testing]
  - pip install flake8

# command to run tests
script:
  - flake8 .
  - pytest --cov=umapviz

after_success:
  - coveralls